# Generated by Django 6.0.5 on 2026-05-13 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_director_movies_movie_actors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ManyToManyField(related_name='reviewed_movies', through='app.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
